/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-pHash.h
 #	source generated by 4D Plugin Wizard
 #	Project : pHash
 #	author : miyako
 #	2019/09/09
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_PHASH_H
#define PLUGIN_PHASH_H

#include "4DPluginAPI.h"

#include <stdio.h>
#include <dirent.h>
#include <errno.h>
#include <vector>
#include <algorithm>
#include <string>
#include <sstream>

#include "pHash.h"

#include "C_LONGINT.h"
#include "C_TEXT.h"
#include "C_REAL.h"

void int64ToParam(ulong64 value, C_TEXT &param);
void paramToPathStr(C_TEXT &param, std::string &path);

#pragma mark -

void PH_Compute_DCT(PA_PluginParameters params);
void PH_Compare_MH(PA_PluginParameters params);
void PH_Compare_RADISH(PA_PluginParameters params);
void PH_Compare_DCT(PA_PluginParameters params);

#endif /* PLUGIN_PHASH_H */
