/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : pHash
 #	author : miyako
 #	2014/06/24
 #
 # --------------------------------------------------------------------------------*/



// --- Compute
void PH_Compute_DCT(sLONG_PTR *pResult, PackagePtr pParams);

// --- Compare
void PH_Compare_MH(sLONG_PTR *pResult, PackagePtr pParams);
void PH_Compare_RADISH(sLONG_PTR *pResult, PackagePtr pParams);
void PH_Compare_DCT(sLONG_PTR *pResult, PackagePtr pParams);
